WebApp/Controllers/PollController.cs
using AutoMapper;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.ViewModels;
using X.PagedList.Extensions;

namespace WebApp.Controllers
{
    public class PollController : Controller
    {
        private readonly PiSudentPollingPlatContext _context;
        private readonly IMapper _mapper;

        public PollController(PiSudentPollingPlatContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        // GET: PollController
        public async Task<IActionResult> Index(int? page, string? searchText, string? sortOrder, int? godinaFilter, int? studijFilter, int? kolegijFilter)
        {
            int pageSize = 4;
            int pageNumber = page ?? 1;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateSortParm"] = string.IsNullOrEmpty(sortOrder) ? "date_desc" : "";

            // Include related data
            IQueryable<Poll> pollsQuery = _context.Polls
                .Include(p => p.Kolegij)
                .Include(p => p.Studij)
                .Include(p => p.Godina);

            // Apply search filter
            if (!string.IsNullOrEmpty(searchText))
            {
                pollsQuery = pollsQuery.Where(p =>
                    p.Title.Contains(searchText) ||
                    (p.Kolegij != null && p.Kolegij.KolegijName.Contains(searchText)) ||
                    (p.Studij != null && p.Studij.StudijName.Contains(searchText)) ||
                    (p.Godina != null && p.Godina.BrojGodine.ToString().Contains(searchText))
                );
            }

            // Apply filters
            if (godinaFilter.HasValue)
            {
                pollsQuery = pollsQuery.Where(p => p.GodinaId == godinaFilter);
            }
            if (studijFilter.HasValue)
            {
                pollsQuery = pollsQuery.Where(p => p.StudijId == studijFilter);
            }
            if (kolegijFilter.HasValue)
            {
                pollsQuery = pollsQuery.Where(p => p.KolegijId == kolegijFilter);
            }

            // Apply sorting
            switch (sortOrder)
            {
                case "date_desc":
                    pollsQuery = pollsQuery.OrderByDescending(p => p.PollDate);
                    break;
                default:
                    pollsQuery = pollsQuery.OrderBy(p => p.PollDate);
                    break;
            }

            var polls = await pollsQuery.ToListAsync();

            // Populate ViewBag for filters
            ViewBag.Godine = new SelectList(await _context.Godinas.ToListAsync(), "Idgodina", "BrojGodine");
            ViewBag.Studiji = new SelectList(await _context.Studijs.ToListAsync(), "Idstudij", "StudijName");
            ViewBag.Kolegiji = new SelectList(await _context.Kolegijs.ToListAsync(), "Idkolegij", "KolegijName");

            ViewData["pages"] = polls.Count / pageSize;
            Response.Cookies.Append("SearchText", searchText ?? "", new CookieOptions { Expires = DateTime.Now.AddDays(7) });
            ViewData["page"] = page;

            return View(polls.ToPagedList(pageNumber, pageSize));
        }

        // GET: PollController/Create
        public ActionResult Create()
        {
            ViewBag.Kolegiji = new SelectList(_context.Kolegijs, "Idkolegij", "KolegijName");
            ViewBag.Studiji = new SelectList(_context.Studijs, "Idstudij", "StudijName");
            ViewBag.Godine = new SelectList(_context.Godinas, "Idgodina", "BrojGodine"); // Populate Godina dropdown
            return View();
        }

        // POST: PollController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(VMPoll poll)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Kolegiji = new SelectList(_context.Kolegijs, "Idkolegij", "KolegijName");
                    ViewBag.Studiji = new SelectList(_context.Studijs, "Idstudij", "StudijName");
                    ViewBag.Godine = new SelectList(_context.Godinas, "Idgodina", "BrojGodine");
                    return View(poll);
                }

                var existingPoll = await _context.Polls.FirstOrDefaultAsync(p => p.Title == poll.Title);
                if (existingPoll != null)
                {
                    ModelState.AddModelError("Name", "A poll with the same title already exists.");
                    ViewBag.Kolegiji = new SelectList(_context.Kolegijs, "Idkolegij", "KolegijName");
                    ViewBag.Studiji = new SelectList(_context.Studijs, "Idstudij", "StudijName");
                    ViewBag.Godine = new SelectList(_context.Godinas, "Idgodina", "BrojGodine");
                    return View(poll);
                }

                var newPoll = _mapper.Map<Poll>(poll);
                newPoll.PollDate = poll.PollDate;
                newPoll.KolegijId = poll.KolegijId;
                newPoll.StudijId = poll.StudijId;
                newPoll.GodinaId = poll.GodinaId;

                _context.Polls.Add(newPoll);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: PollController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PollController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PollController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var poll = _context.Polls.FirstOrDefault(x => x.Id == id);
                var pollVM = new VMPoll
                {
                    Id = poll.Id,
                    Title = poll.Title,
                    Tekst = poll.Tekst,
                };

                return View(pollVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: PollController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, VMPoll poll)
        {
            try
            {
                var dbPoll = _context.Polls.FirstOrDefault(x => x.Id == id);
                _context.Polls.Remove(dbPoll);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

WebApp/Controllers/QuestionController.cs
using AutoMapper;
using DAL.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class QuestionController : Controller
    {

        private readonly PiSudentPollingPlatContext _context;
        private readonly IMapper _mapper;

        public QuestionController(PiSudentPollingPlatContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        // GET: QuestionController
        public ActionResult Index(int id)
        {
            try
            {
                var questionsVms = _context.Questions.Select(x => new VMQuestion
                {
                    Id = x.Id,
                    Tekst = x.Tekst,
                    PollId = x.PollId,

                }).ToList().Where(x => x.PollId.Equals(id));

                return View(questionsVms);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: QuestionController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var question = _context.Questions.FirstOrDefault(x => x.Id == id);
                var questionVM = new VMQuestion
                {
                    Id = question.Id,
                    Tekst = question.Tekst,
                    PollId = question.PollId
                };

                return View(questionVM);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }

        // GET: QuestionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuestionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VMQuestion question)
        {
            try
            {
                var newQuestion = new Question
            {
                Id = question.Id,
                Tekst = question.Tekst,
                PollId = question.PollId
            };

            _context.Questions.Add(newQuestion);

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
            catch
            {
                return View();
    }
}


        // GET: QuestionController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var question = _context.Questions.FirstOrDefault(x => x.Id == id);
                var questionVM = new VMQuestion
                {
                    Id = question.Id,
                    Tekst = question.Tekst,
                    PollId = question.PollId
                };

                return View(questionVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: QuestionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, VMQuestion question)
        {
            try
            {
                var dbQuestion = _context.Questions.FirstOrDefault(x => x.Id == id);
                dbQuestion.Id = question.Id;
                dbQuestion.Tekst = question.Tekst;
                dbQuestion.PollId = question.PollId;

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // GET: QuestionController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var question = _context.Questions.FirstOrDefault(x => x.Id == id);
                var questionVM = new VMQuestion
                {
                    Id = question.Id,
                    Tekst = question.Tekst,
                    PollId = question.PollId
                };

                return View(questionVM);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        // POST: QuestionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, VMQuestion quesiton)
        {
            try
            {
                var dbComment = _context.Questions.FirstOrDefault(x => x.Id == id);

                _context.Questions.Remove(dbComment);

                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

WebApp/Views/Poll/Create.cshtml
@model WebApp.ViewModels.VMPoll

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Tekst" class="control-label"></label>
                <input asp-for="Tekst" class="form-control" />
                <span asp-validation-for="Tekst" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PollDate" class="control-label"></label>
                <input asp-for="PollDate" class="form-control" type="date" />
                <span asp-validation-for="PollDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="KolegijId" class="control-label"></label>
                <select asp-for="KolegijId" asp-items="ViewBag.Kolegiji" class="form-control">
                    <option value="">Select Kolegij</option>
                </select>
                <span asp-validation-for="KolegijId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StudijId" class="control-label"></label>
                <select asp-for="StudijId" asp-items="ViewBag.Studiji" class="form-control">
                    <option value="">Select Studij</option>
                </select>
                <span asp-validation-for="StudijId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="GodinaId" class="control-label"></label>
                <select asp-for="GodinaId" asp-items="ViewBag.Godine" class="form-control">
                    <option value="">Select Godina</option>
                </select>
                <span asp-validation-for="GodinaId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

WebApp/Views/Poll/Delete.cshtml
@model WebApp.ViewModels.VMPoll

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tekst)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tekst)
        </dd>

    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Views/Poll/Edit.cshtml
@model WebApp.ViewModels.VMPoll

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Tekst" class="control-label"></label>
                <input asp-for="Tekst" class="form-control" />
                <span asp-validation-for="Tekst" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PollDate" class="control-label"></label>
                <input asp-for="PollDate" class="form-control" type="date" />
                <span asp-validation-for="PollDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="KolegijId" class="control-label"></label>
                <select asp-for="KolegijId" asp-items="ViewBag.Kolegiji" class="form-control">
                    <option value="">Select Kolegij</option>
                </select>
                <span asp-validation-for="KolegijId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="StudijId" class="control-label"></label>
                <select asp-for="StudijId" asp-items="ViewBag.Studiji" class="form-control">
                    <option value="">Select Studij</option>
                </select>
                <span asp-validation-for="StudijId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebApp/Views/Poll/Index.cshtml
@model X.PagedList.IPagedList<DAL.Models.Poll>
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Index";
    string searchText = HttpContextAccessor.HttpContext.Request.Cookies["SearchText"];
    var page = (int?)ViewData["page"];
    var pages = (int?)ViewData["pages"];
}

<h1>Polls</h1>
<a asp-action="Create" class="btn btn-primary mb-3 mt-3">Create new Poll</a>

<!-- Filter Form -->
<form method="get" class="mb-3">
    <div class="row">
        <div class="col-md-3">
            <label for="searchValue">Search:</label>
            <input id="searchValue" type="search" name="searchText" class="form-control" placeholder="Search by Poll Title" value="@searchText" />
        </div>
        <div class="col-md-3">
            <label for="godinaFilter">Filter by Godina:</label>
            @Html.DropDownList("godinaFilter", (IEnumerable<SelectListItem>)ViewBag.Godine, "All Years", new { @class = "form-control", id = "godinaFilter" })
        </div>
        <div class="col-md-3">
            <label for="studijFilter">Filter by Studij:</label>
            @Html.DropDownList("studijFilter", (IEnumerable<SelectListItem>)ViewBag.Studiji, "All Studij", new { @class = "form-control", id = "studijFilter" })
        </div>
        <div class="col-md-3">
            <label for="kolegijFilter">Filter by Kolegij:</label>
            @Html.DropDownList("kolegijFilter", (IEnumerable<SelectListItem>)ViewBag.Kolegiji, "All Kolegij", new { @class = "form-control", id = "kolegijFilter" })
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Search/Apply Filters</button>
        </div>
    </div>
</form>

<!-- Sorting Options -->
<div class="mt-3">
    <span>Sort by: </span>
    <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" class="btn btn-secondary">Date</a>
</div>

<!-- Poll Cards -->
<div class="row" id="poll-cards-row">
    @foreach (var poll in Model)
    {
        <div class="col-md-3">
            <div class="card mb-3 h-100">
                <div class="card-body">
                    <h5 class="card-title">@poll.Title</h5>
                    <p class="card-text">@poll.Tekst</p>
                    <p class="card-text">
                        <small class="text-muted">Date: @poll.PollDate?.ToString("yyyy-MM-dd")</small>
                    </p>
                    <p class="card-text">
                        <small class="text-muted">Kolegij: @(poll.Kolegij?.KolegijName ?? "None")</small>
                    </p>
                    <p class="card-text">
                        <small class="text-muted">Studij: @(poll.Studij?.StudijName ?? "None")</small>
                    </p>
                    <p class="card-text">
                        <small class="text-muted">Godina: @(poll.Godina?.BrojGodine?.ToString() ?? "None")</small>
                    </p>
                </div>
                <div class="card-footer">
                    <a asp-action="Index" asp-route-id="@poll.Id" asp-controller="Question" class="btn btn-primary">Questions</a>
                    <a asp-action="Edit" asp-route-id="@poll.Id" class="btn btn-secondary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@poll.Id" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    }
    

</div>

<!-- Pagination -->
<div class="btn-group mt-2">
    <div class="mt-2 mb-2">Page size: 4 -></div>
    @for (var i = 1; i <= pages + 1; i++)
    {
        var currClass = page == i ? "btn-primary" : "btn-outline-primary";
        <a asp-action="Index"
           asp-route-page="@i"
           data-page="@i"
           class="pager-btn btn @currClass">@(i)</a>
    }
</div>

@section Scripts {
    <script>
        $(".pager-btn").click(function (event) {
            console.log("Pager button clicked");
            event.preventDefault();

            var page = $(this).data("page");

            var ajaxData = {
                page: page,
                searchText: document.getElementById("searchValue").value
            };

            $.ajax({
                type: "GET",
                url: "/Poll/Index",
                data: ajaxData,
                success: function (data) {
                    $("#poll-cards-row").html(data);

                    $(".pager-btn").removeClass("btn-primary");
                    $(".pager-btn").addClass("btn-outline-primary");

                    $(".pager-btn[data-page=" + page + "]").removeClass("btn-outline-primary");
                    $(".pager-btn[data-page=" + page + "]").addClass("btn-primary");
                },
                error: function (data) {
                    console.error("Ajax GET error", data);
                }
            });
        });
    </script>
}

WebApp/Views/Poll/_PollsCardsPartial.cshtml
@model IEnumerable<DAL.Models.Poll>

@foreach (var item in Model)
{
    <div class="col-md-3">
        <div class="card mb-3 h-100">
            <div class="card-body">
                <h5 class="card-title">@item.Title</h5>
                <p class="card-text">Odgovori: @item.Tekst</p>
            </div>
            <div class="card-footer">
                <a asp-action="Index" asp-route-id="@item.Id" asp-controller="Question" class="btn btn-primary">Questions</a>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary">Edit</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>
}
